# Generated by Django 6.0.6 on 2026-07-19 00:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estatus', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias_media/')),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='mesas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_mesa', models.IntegerField()),
                ('estatus', models.CharField(choices=[('eliminado', 'Eliminado'), ('disponible', 'Disponible'), ('ocupado', 'Ocupado')], default='disponible', max_length=20)),
            ],
            options={
                'db_table': 'mesas',
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('cliente', 'Cliente'), ('mesero', 'Mesero'), ('cajero', 'Cajero'), ('admin', 'Admin')], default='cliente', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usuarios_media')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ordenes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estatus', models.CharField(choices=[('eliminado', 'Eliminado'), ('habilitado', 'Habilitado'), ('pidiendo', 'Pidiendo'), ('cocinando', 'Cocinando'), ('finalizado', 'Finalizado'), ('delivery', 'Delivery'), ('entregado', 'Entregado'), ('pagado', 'Pagado')], default='pidiendo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(limit_choices_to={'role': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='mis_ordenes', to=settings.AUTH_USER_MODEL)),
                ('mesa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mesas')),
                ('mesero', models.ForeignKey(blank=True, limit_choices_to={'role': 'mesero'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estatus', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos_media/')),
                ('categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorias')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='detallesOrdenes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estatus', models.BooleanField(default=True)),
                ('orden_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.ordenes')),
                ('producto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_en_ordenes', to='core.productos')),
            ],
            options={
                'db_table': 'detalles_ordenes',
            },
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='comentarios_media/')),
                ('estatus', models.BooleanField(default=True)),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
            ],
            options={
                'db_table': 'favoritos',
                'unique_together': {('usuario_fk', 'producto_fk')},
            },
        ),
    ]
