# Generated by Django 6.0.6 on 2026-06-23 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Ordenes',
        ),
        migrations.AlterModelTable(
            name='categorias',
            table='Categorias',
        ),
        migrations.AlterModelTable(
            name='mesas',
            table='Mesas',
        ),
        migrations.AlterModelTable(
            name='ordenes',
            table='Ordenes',
        ),
        migrations.AlterModelTable(
            name='productos',
            table='Productos',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='Usuarios',
        ),
    ]
