# Generated by Django 6.0.7 on 2026-07-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='calificacion',
            field=models.IntegerField(choices=[(1, 'No me gustó mucho'), (2, 'No me gustó'), (3, 'No es de mi agrado'), (4, 'Me gustó'), (5, 'Me gustó mucho')], default=5),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
