# Generated by Django 6.0.6 on 2026-06-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_order_ordenes_alter_categorias_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_media/'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios_media'),
        ),
    ]
